### ISSUE TITLE
Commify Values (Implementation suggestion included)

### ISSUE THREAD

**Issue by Somnioblivio** [DJDajn/Accountant#13]
First off thank you SO much for this mod, i love being able to summarize how well (or not so well) i performed monetarily throughout the week, and this mod is the perfect lightweight solution to do that! 

**Onto the suggestion:**
As i'm sure you are well aware, Gold amounts regularly soar into the millions these days often making them troublesome to read without commas.

The following regex (that was a bitch for me to figure out initially) fixes that by reading the value and adding commas in standard format:

`string.gsub(goldcom, "^(-?%d+)(%d%d%d)", '%1,%2')`

I have been patching a fix in myself since atleast WoD via the following:

_editing the the SC.NiceCash Function of the main .lua file_

_Added a local variable_
`local goldcom = gold`

_and then at about line 1835:_
```
		if gold > 0 then
			goldcom = gold	
			while true do 
				goldcom, k = string.gsub(goldcom, "^(-?%d+)(%d%d%d)", '%1,%2')
				if (k==0) then
				break
				end
			end

			gold_str = gc..(goldcom or "?").."g "..FONT_COLOR_CODE_CLOSE

```

**Conclusion**
This makes the output much easier to read as you can see in this example here:
https://i.imgur.com/YGAduQL.png

i'm pretty sure there is an even easier way to do something like this, but this is what i came up with in a pinch (and last ditch effort to not be forced to drop the mod cause it was frustrating without it)

Hope this suggestion finds you well and i would like to again extend my thanks for this addon, I consider it a staple of any UI build and have been using it for years...

Thanks!!

**Comment by DJDajn** [comment]
Hey Somnioblivio, thanks for the great suggestion!
This is something that I haven't even thought about adding before you mentioned it and it will be added in the next version of the addon. (With credits in the change log) :)

With regards,
Dajn

**Comment by Somnioblivio** [comment]
Dajn, Thanks a ton man!!!
