### ISSUE TITLE
Previous Version worked with titan panel, new version (only just updated) doesnt

### ISSUE THREAD

**Issue by BeLZeDaR666** [DJDajn/Accountant#2]
Hi up until i updated accountant about 3 minutes ago  it always appeared and worked since being updated to work with 8..x, however with your latest version (8.0.1.11) it no longer appears in the titan panel bars and the option for the module when I try to select through titan panel is no longer there. 

However I stepped back to the earlier version (8.0,1) and it works fine again. hope this helps in some way

**Comment by DJDajn** [comment]
Should work with 8.0.1.12, so if you can go ahead and check it would be great. :)

With regards,
Dajn

**Comment by DJDajn** [comment]
Closing this issue, if you still have problems with the newest version (8.0.1.12), make a new issue.

With regards,
Dajn
