### ISSUE TITLE
LUA error at the mailbox

### ISSUE THREAD

**Issue by Urdui** [DJDajn/Accountant#6]
I get this error when retrieving gold from the mailbox:

Message: Interface\AddOns\Accountant\Accountant.lua:1720: bad argument #1 to 'find' (string expected, got nil)
Time: Sun Aug  5 14:29:51 2018
Count: 4
Stack: Interface\AddOns\Accountant\Accountant.lua:1720: bad argument #1 to 'find' (string expected, got nil)
[C]: in function `find'
Interface\AddOns\Accountant\Accountant.lua:1720: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: (*temporary) = nil
(*temporary) = "Outbid"
(*temporary) = "string expected, got nil"

**And on another charcter with the same thing the count increased even when there was no gold attached to the mail, but an item was:**

Message: Interface\AddOns\Accountant\Accountant-8.0.1.15.lua:1720: bad argument #1 to 'find' (string expected, got nil)
Time: Sun Aug  5 14:43:53 2018
Count: 46
Stack: Interface\AddOns\Accountant\Accountant-8.0.1.15.lua:1720: bad argument #1 to 'find' (string expected, got nil)

Locals: 

There is no error when retrieving gold from selling an item to a vendor, or

**Comment by DJDajn** [comment]
What version of the addon are you using?

If you get back to me, then I'll look into this.  :)

With regards,
Dajn

Edit: Nevermind, just saw the Version in the error text xD

**Comment by raysmith59** [comment]
I just got this as well, specifically my DK was taking one of his class hall mounts (Reins of the Deathcharger) out of the mailbox (when you already have one and try to get another one from the class hall it goes to your mailbox via the Postmaster, which is handy... I was just removing one to use).  Not sure if the item being removed matters or not yet but based on the earlier report and my experience, probably not.  I'm going to revert to the previous version for now.

Message: Interface\AddOns\Accountant\Accountant-8.0.1.15.lua:1720: bad argument #1 to 'find' (string expected, got nil)
Time: Sun Aug  5 21:24:37 2018
Count: 1
Stack: Interface\AddOns\Accountant\Accountant-8.0.1.15.lua:1720: bad argument #1 to 'find' (string expected, got nil)

Locals:

**Comment by DJDajn** [comment]
This is now fixed in the 8.0.1.16 version (Out later today).
If anything else comes up, please report it. :)

With regards,
Dajn
