### ISSUE TITLE
Weekly Reset Malfunction

### ISSUE THREAD

**Issue by Urdui** [DJDajn/Accountant#7]
Accountant is not properly resetting the week when it expires.

I have my "Beginning of week" set to Tuesday when all the weekly stuff in WOW resets, but this week Accountant did not reset, it continues to add to my previous week. There is no LUA error flagged that I can see.

**Comment by DJDajn** [comment]
Sorry for the late response, been leveling my characters to 120 this week :p  
Cant reproduce this, so can you change the day that the week resets on and change it back again? This will force it to clear the week and start fresh.

If it wont reset next week just write a reply on this post and I'll look into it again. :)

With regards,
Dajn

**Comment by Urdui** [comment]
On Friday I changed the day and forced the reset, which only happened after I reloaded my UI. I then set my weekly reset for Saturday and continued playing all Friday night. Today is Saturday. When logging in there is no reset. I can still see my weekly total from Friday night. I'll make another attempt and change it back to Tuesday and check again to make sure.

**Comment by Urdui** [comment]
Switched to Tuesday reset on Saturday. On Tuesday no reset. Is there a specific time it's supposed to reset on the chosen day? I was playing at midnight Tuesday on a different character an noticed no reset then. I think I've seen it reset live in the past at that time. Either way there was no reset logging on to my main character Tuesday afternoon.

**Comment by Elbryan01** [comment]
I have the same problem. I have set it to reset wednesday but it have not reset this morning

**Comment by DJDajn** [comment]
Cant look into this until the weekend as there is a lot going on at work atm, but as it's a core thing in the addon it will be prioritized before anything else is handled. :)

**Comment by DJDajn** [comment]
Rewrote the week reset handling and everything works fine again now. New version will be out asap. :)

With regards,
Dajn

**Comment by DJDajn** [comment]
@Elbryan01 and @Urdui, Is the new week reset working for you guys? Just need to confirm if it's just one user that have a problem or if it is multiple users. :)

With regards,
Dajn

**Comment by Urdui** [comment]
No, it did not reset this week again. I have done a complete reinstall of the add-on and will test again for next week.

**Comment by Elbryan01** [comment]
Mine didn't reset either. I have now done a complete reinstall and set the reset date to friday and I will see if it resets tomorrow.
I have however found another issue where the display of your gold (sess, day, week, tot) on the minimap button also control what is shown on your data broker bar.

**Comment by Elbryan01** [comment]
It did reset this morning so it seem to be working now
