### ISSUE TITLE
Clear Data is giving a LUA error

### ISSUE THREAD

**Issue by raysmith59** [DJDajn/Accountant#8]
I went into the Accounting interface settings in order to clear the data going into the new expansion and got this LUA error.  Seems to be cosmetic just in terms of displaying a chat message so I've commented it out for now.

2x AceLocale-3.0-6: Accountant: Missing entry for 'Accountant: clear data complete'
Accountant\Accountant-8.0.1.16.lua:416: in function <Accountant\Accountant.lua:414>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-66.lua:818: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[4]"]:9: in function <[string "safecall Dispatcher[4]"]:5>
(tail call): ?
...aceAccountant\Libs\AceGUI-3.0\AceGUI-3.0-36.lua:314: in function `Fire'
...tant\Libs\AceGUI-3.0-36\widgets\AceGUIWidget-Button.lua:22: in function <...tant\Libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by DJDajn** [comment]
This will be fixed in the next version, need to fix some other stuff as well before I release it tho
